server:
  port: 60101
spring:
  application:
    name: ginkgo-id-service
  datasource:
    url: jdbc:mysql://localhost:3306/gk_id?useSSL=true&serverTimezone=Asia/Shanghai
    username: temp
    password: 123
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml

dubbo:
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  application:
    name: ${spring.application.name}
    logger: slf4j